### ISSUE TITLE
[FEAT] Handle entity attributes

### ISSUE THREAD

**Issue by zoic21** [coltondick/ansible_playbook_monitor#1]
Hello,

To begin thanks for your integration, before that I used mqtt but it's easier with your integration. I have a small request can you add attribute management ? I want to do something like that : 

```
- name: Notify Home Assistant of Playbook Start
  hosts: localhost
  tasks:
    - name: Notify HA webhook of playbook start
      uri:
        url: "http://your-home-assistant-instance/api/webhook/ansible_playbook_monitor_webhook"
        method: POST
        headers:
          Authorization: "Bearer YOUR_API_KEY" # Replace with your actual API key
          Content-Type: "application/json"
        body: '{"playbook": "deploy_app", "status": "started", "attributes" : {"result" : 10, "datetime" : "XXXXXXX"}}'
        body_format: json
```

And find my attributes on attributes entity. It's can be usefull to pass resultat like number of waiting update on system for exemple.

Thanks in advance,
